package io.httpdoc.objc;

import io.httpdoc.core.Category;
import io.httpdoc.core.Constant;
import io.httpdoc.core.Property;
import io.httpdoc.core.Schema;
import io.httpdoc.core.exception.SchemaDesignException;
import io.httpdoc.core.modeler.Archetype;
import io.httpdoc.core.modeler.Modeler;
import io.httpdoc.core.reflection.ParameterizedTypeImpl;
import io.httpdoc.core.supplier.Supplier;
import io.httpdoc.core.type.HDType;
import io.httpdoc.objc.fragment.*;
import io.httpdoc.objc.type.ObjCClass;
import io.httpdoc.objc.type.ObjCType;

import java.util.*;

/**
 * @author 杨昌沛 646742615@qq.com
 * @date 2018-07-25 16:37
 **/
public class MJExtensionModeler implements Modeler<ObjCFile> {
    private final String prefix;

    public MJExtensionModeler(String prefix) {
        this.prefix = prefix;
    }

    /**
     * 设计
     *
     * @param archetype 原型
     * @return 模型
     * @throws SchemaDesignException Schema 不可设计的异常
     */
    @Override
    public Collection<ObjCFile> design(Archetype archetype) throws SchemaDesignException {
        final String comment = "Generated By Httpdoc";
        final String pkgGenerated = archetype.getPkg();
        final boolean pkgForced = archetype.isPkgForced();
        final Supplier supplier = archetype.getSupplier();
        final Schema schema = archetype.getSchema();
        final String pkgTranslated = schema.getPkg();
        final String pkg = pkgForced || pkgTranslated == null ? pkgGenerated : pkgTranslated;
        final String name = schema.getName();

        switch (schema.getCategory()) {
            case ENUM: {
                EnumInterfaceFragment interfase = new EnumInterfaceFragment();
                interfase.setName(prefix + name);
                interfase.setCommentFragment(new CommentFragment(schema.getDescription() != null ? schema.getDescription() + "\n" + comment : comment));
                Set<Constant> constants = schema.getConstants();
                for (Constant constant : (constants != null ? constants : Collections.<Constant>emptySet())) {
                    interfase.addExportFragment(constant.getDescription(), prefix + name + constant.getName());
                }

                EnumImplementationFragment implementation = new EnumImplementationFragment();
                implementation.setName(prefix + name);
                implementation.setCommentFragment(new CommentFragment(schema.getDescription() != null ? schema.getDescription() + "\n" + comment : comment));
                for (Constant constant : (constants != null ? constants : Collections.<Constant>emptySet())) {
                    implementation.addAssignFragment(constant.getDescription(), prefix + name + constant.getName(), constant.getName());
                }

                return Arrays.asList(new ObjCFile(pkg, interfase), new ObjCFile(pkg, implementation));
            }
            case OBJECT: {
                ClassInterfaceFragment interfase = new ClassInterfaceFragment();
                interfase.setName(prefix + name);
                interfase.setCommentFragment(new CommentFragment(schema.getDescription() != null ? schema.getDescription() + "\n" + comment : comment));
                Schema superclass = schema.getSuperclass();
                interfase.setSuperclass(superclass != null && superclass.getCategory() == Category.OBJECT ? (ObjCClass) superclass.toType(pkgGenerated, pkgForced, supplier) : null);
                Map<String, Property> properties = schema.getProperties();
                for (Map.Entry<String, Property> entry : (properties != null ? properties.entrySet() : Collections.<Map.Entry<String, Property>>emptySet())) {
                    Property property = entry.getValue();
                    ObjCType type = (ObjCType) property.getType().toType(pkgGenerated, pkgForced, supplier);
                    PropertyFragment propertyFragment = new PropertyFragment();
                    propertyFragment.setName(entry.getKey());
                    propertyFragment.setType(type);
                    propertyFragment.setCommentFragment(new CommentFragment(property.getDescription()));
                    interfase.addPropertyFragment(propertyFragment);
                }

                ClassImplementationFragment implementation = new ClassImplementationFragment();
                interfase.setName(prefix + name);
                implementation.setCommentFragment(new CommentFragment(schema.getDescription() != null ? schema.getDescription() + "\n" + comment : comment));

                SelectorFragment objectClassInArrayMethod = getObjectClassInArrayMethodFragment(pkgForced, supplier, pkg, properties);
                if (objectClassInArrayMethod != null) implementation.addSelectorFragment(objectClassInArrayMethod);

                SelectorFragment replacedKeyFromPropertyNameMethod = getReplacedKeyFromPropertyNameMethodFragment(pkgForced, supplier, pkg, properties);
                if (replacedKeyFromPropertyNameMethod != null) implementation.addSelectorFragment(replacedKeyFromPropertyNameMethod);

                return Arrays.asList(new ObjCFile(pkg, interfase), new ObjCFile(pkg, implementation));
            }
            default:
                return Collections.emptySet();
        }
    }

    private SelectorFragment getReplacedKeyFromPropertyNameMethodFragment(boolean pkgForced, Supplier supplier, String pkg, Map<String, Property> properties) {
        SelectorFragment selector = new SelectorFragment();
        selector.setInstantial(false);
        selector.setName("mj_replacedKeyFromPropertyName");
        ResultFragment objectClassInArrayResult = new ResultFragment();
        objectClassInArrayResult.setType(ObjCType.valueOf(prefix, HDType.valueOf(new ParameterizedTypeImpl(Map.class, new Class<?>[]{String.class, String.class}))));
        selector.setResultFragment(objectClassInArrayResult);
        BlockFragment block = new BlockFragment();
        block.getSentences().add("return @{");
        int count = 0;
        for (Map.Entry<String, Property> entry : (properties != null ? properties.entrySet() : Collections.<Map.Entry<String, Property>>emptySet())) {
            Property property = entry.getValue();
            String name = entry.getKey();
            String alias = property.getAlias();
            if (alias == null || alias.equals(name)) continue;
            String sentence = "    @\"" + alias + "\": @\"" + name + "\"" + (count++ > 0 ? "," : "");
            block.getSentences().add(1, sentence);
        }
        block.getSentences().add("};");
        selector.setBlockFragment(block);
        return count > 0 ? selector : null;
    }

    private SelectorFragment getObjectClassInArrayMethodFragment(boolean pkgForced, Supplier supplier, String pkg, Map<String, Property> properties) {
        SelectorFragment selector = new SelectorFragment();
        selector.setInstantial(false);
        selector.setName("mj_objectClassInArray");
        ResultFragment objectClassInArrayResult = new ResultFragment();
        objectClassInArrayResult.setType(ObjCType.valueOf(prefix, HDType.valueOf(new ParameterizedTypeImpl(Map.class, new Class<?>[]{String.class, String.class}))));
        selector.setResultFragment(objectClassInArrayResult);
        BlockFragment block = new BlockFragment();
        block.getSentences().add("return @{");
        int count = 0;
        for (Map.Entry<String, Property> entry : (properties != null ? properties.entrySet() : Collections.<Map.Entry<String, Property>>emptySet())) {
            Property property = entry.getValue();
            Schema type = property.getType();
            Category category = type.getCategory();
            Schema component = type.getComponent();
            if (category == Category.ARRAY) {
                while (component.getCategory() == Category.ARRAY) component = component.getComponent();
                ObjCClass componentType = (ObjCClass) component.toType(pkg, pkgForced, supplier);
                CharSequence className = componentType.getName();
                className = componentType.isPrimitive() ? "NSNumber" : className;
                String sentence = "    @\"" + entry.getKey() + "\": @\"" + className + "\"" + (count++ > 0 ? "," : "");
                block.getSentences().add(1, sentence);
            }
        }
        block.getSentences().add("};");
        selector.setBlockFragment(block);
        return count > 0 ? selector : null;
    }

}
